"""The exp_07 record generators run on real producer outputs over synthetic runs."""
import json
import re
from pathlib import Path

import pytest

from exp07_fixture import exp07_fixture  # noqa: F401  (fixture)
from test_paired_compare import admission_fixture  # noqa: F401  (table_fixture needs it)
from test_results_table import table_fixture  # noqa: F401  (exp_04's unseen table)
from tools import exp07_pairs as pairs_producer, exp07_table as table_producer
from tools import results_table as rt
from tools.exp07_profiles import get_profile, json_value
from tools.exp07_record import load_asset

ROLES = ('seen_cyl', 'seen_aug', 'released_seen')


def sidecar(path):
    return Path(str(path) + '.provenance.json')


@pytest.fixture
def record_inputs(exp07_fixture, table_fixture, tmp_path):  # noqa: F811
    """One synthetic run layout published through both exp_07 producers, plus exp_04's."""
    md = load_asset('make_results_md')
    built = exp07_fixture()
    built.profile['n_boot'] = 2000
    results = tmp_path / 'results'
    results.mkdir()
    paths = dict(table=results / 'TABLE_SEEN_V1.json', pairs=[])
    table, admitted = table_producer.build_table(built.directories, built.profile,
                                                 built.approved, producer=built.producer)
    table_producer.write_outputs(table, admitted, str(paths['table']),
                                 str(results / 'model_comparison_seen.md'),
                                 command=['exp07_table.py'])
    profile = json_value(get_profile('PAIRS_SEEN_V1'))
    profile.update(n_boot=2000, **{key: built.profile[key] for key in
                                   ('dataset', 'arms', 'seeds', 'train_inventory_files')})
    for role in ROLES:
        sides = [[path for shot in (8, 1) for path in built.paths[(item, shot)]]
                 for item in (role, 'seen_simple')]
        result, admitted = pairs_producer.build_pairs(*sides, profile=profile,
                                                      approved=built.approved,
                                                      producer=built.producer)
        paths['pairs'].append(results / ('PAIRS_SEEN_V1_' + role + '.json'))
        pairs_producer.write_outputs(result, admitted, str(paths['pairs'][-1]),
                                     str(results / (role + '.summary.txt')),
                                     pairs_producer.render_summary)
    unseen, admitted = rt.build_table(table_fixture.directories)
    paths['unseen'] = results / 'TABLE_V1.json'
    rt.write_outputs(unseen, admitted, str(paths['unseen']), str(results / 'model_comparison.md'))
    published = json.loads(sidecar(paths['unseen']).read_text())['outputs']
    paths['binding'] = results / 'binding_report_20260915T000000000000Z.json'
    paths['binding'].write_text(json.dumps(dict(schema_version=1, git_HEAD='b' * 40, results=[
        dict(profile='TABLE_V1', producer_commit='b' * 40,
             sidecar=dict(path=str(sidecar(paths['unseen'])),
                          sha256=md.sha(sidecar(paths['unseen']).read_bytes())),
             outputs=[dict(path=path, sha256=digest)
                      for path, digest in sorted(published.items())])]), indent=1))
    paths['out'] = tmp_path / 'seen_protocol_results.md'
    return paths


def argv(paths, **changes):
    values = dict(table=paths['table'], pairs=paths['pairs'], unseen_table=paths['unseen'],
                  unseen_binding=paths['binding'], out=paths['out'])
    values.update(changes)
    return (['--table', str(values['table']), '--pairs'] + [str(p) for p in values['pairs']] +
            ['--unseen-table', str(values['unseen_table']), '--unseen-binding',
             str(values['unseen_binding']), '--out', str(values['out'])])


def test_the_generator_admits_the_complete_record(record_inputs):
    md = load_asset('make_results_md')
    args, record, head = md.arguments(argv(record_inputs))
    assert len(record['table']['rows']) == 8 and len(record['pairs']) == 3
    assert sum(len(data['cells']) for data in record['pairs']) == 30
    assert sorted(tuple(data['pairing']) for data in record['pairs']) == sorted(md.PAIRINGS)
    assert len(record['unseen']['rows']) == 6 and len(record['receipts']) == 5
    assert record['receipts'][-1]['binding_report']['path'] == str(record_inputs['binding'])
    assert len(head) == 40 and args.out == str(record_inputs['out'])


NUMBERS = r'(?<![\w.])[-+]?\d+(?:\.\d+)?(?:e[-+]?\d+)?(?![\w])'
VERDICT_WORDS = ('verdict', 'significant', 'non-inferior', 'superior', 'equivalent',
                 'p-value', 'better than', 'worse than', 'wins')


def test_the_markdown_is_canonical_and_byte_stable(record_inputs):
    md = load_asset('make_results_md')
    md.main(argv(record_inputs))
    first = record_inputs['out'].read_text()
    md.main(argv(record_inputs))
    assert first == record_inputs['out'].read_text()
    assert first.startswith('generated by make_results_md.py from ')
    assert md.ROUNDING in first and md.DESCRIPTIVE in first
    for title in ('Seen split', 'Descriptive paired differences', 'Seen and unseen protocols',
                  'Provenance'):
        assert '## ' + title in first
    assert first.index('Seen split') < first.index('Descriptive paired')
    assert first.index('Descriptive paired') < first.index('Seen and unseen protocols')
    assert first.index('Seen and unseen protocols') < first.index('## Provenance')
    cells = '\n'.join(line for line in first.split('\n') if line.startswith('|'))
    assert not any(word in cells.lower() for word in VERDICT_WORDS)  # the disclaimer names them
    assert '{' not in first and '[' not in first


def test_every_rendered_number_comes_from_the_canonical_json(record_inputs):
    md = load_asset('make_results_md')
    md.main(argv(record_inputs))
    rendered = record_inputs['out'].read_text().split('\n')
    sources = [record_inputs['table'], record_inputs['unseen']] + record_inputs['pairs']
    raw = ''.join(Path(path).read_text() + sidecar(path).read_text() for path in sources)
    allowed = set(re.findall(NUMBERS, raw))
    allowed |= {format(float(value) * scale, spec) for value in list(allowed)
                for scale in (1, .001, 100, 1000)
                for spec in ('.1f', '.2f', '.3f', '.6g')}
    allowed.add('95')  # the '95% interval' column labels are the only numeric literals
    assert set(re.findall(NUMBERS, '\n'.join(rendered[4:]))) <= allowed


def test_the_tables_report_the_producers_own_values(record_inputs):
    md = load_asset('make_results_md')
    _, record, head = md.arguments(argv(record_inputs))
    md.main(argv(record_inputs))
    text = record_inputs['out'].read_text()
    assert head in text
    for row in record['table']['rows']:
        edt = row['metrics']['EDT']
        assert '{} s ± {} ms'.format(format(edt['mean'] / 1000, '.3f'),
                                     md.display(edt['sd'], 'EDT')) in text
        assert '{} ± {} dB'.format(*[md.display(row['metrics']['C50'][key], 'C50')
                                     for key in ('mean', 'sd')]) in text
        assert row['label'] in text
    for data in record['pairs']:
        for cell in data['cells']:
            relative = cell['statistics']['relative']
            assert md.percent(relative['estimate']) in text
            assert md.percent(relative['convergence']['ratio']) in text
            assert md.native(cell['metric'], cell['statistics']['absolute']['estimate']) in text
    for receipt in record['receipts']:
        assert receipt['sha256'] in text and receipt['profile_digest'] in text
        assert receipt['approved_digests']['sha256'] in text
    assert record['receipts'][-1]['binding_report']['sha256'] in text


def test_the_combined_table_pairs_each_seen_arm_with_its_unseen_row(record_inputs):
    md = load_asset('make_results_md')
    _, record, head = md.arguments(argv(record_inputs))
    title, headers, rows = list(md.tables(record, head))[2]
    assert title.startswith('Seen and unseen protocols')
    assert [row[1] for row in rows] == [1] * 4 + [8] * 4
    unseen = {(row['role'], row['num_shot']): row for row in record['unseen']['rows']}
    seen = {(row['role'], row['num_shot']): row for row in record['table']['rows']}
    for index, (seen_role, unseen_role) in enumerate(md.PROTOCOL_PAIRS):
        row = rows[index]
        assert row[0] == seen[(seen_role, 1)]['label']
        assert row[2] == md.mean_sd(seen[(seen_role, 1)]['metrics'], 'EDT')
        assert row[5] == md.mean_sd(unseen[(unseen_role, 1)]['metrics'], 'EDT')
    assert rows[3][0] == seen[(md.REFERENCE_ROLE, 1)]['label'] and rows[3][5:] == ['—'] * 3


def test_the_html_page_is_offline_stable_and_shows_the_same_cells(record_inputs):
    html, md = load_asset('make_results_html'), load_asset('make_results_md')
    out = record_inputs['out'].with_suffix('.html')
    html.main(argv(record_inputs, out=out))
    first = out.read_text()
    html.main(argv(record_inputs, out=out))
    assert first == out.read_text() and first.startswith('<!doctype html>')
    assert '<script' not in first and 'http://' not in first and 'https://' not in first
    assert first.count('<table>') == 5 and first.rstrip().endswith('</html>')
    _, record, head = md.arguments(argv(record_inputs))
    for title, headers, rows in md.tables(record, head):
        assert '<h2>' + html.esc(title) + '</h2>' in first
        for row in rows:
            assert all('<td>' + html.esc(value) + '</td>' in first for value in row)


def test_the_html_page_refuses_the_same_input_the_markdown_refuses(record_inputs):
    html = load_asset('make_results_html')
    MUTATIONS['pairs_reconverge'](record_inputs)
    out = record_inputs['out'].with_suffix('.html')
    with pytest.raises(ValueError, match='not final'):
        html.main(argv(record_inputs, out=out))
    assert not out.exists()


def edit(path, mutate, restamp=True):
    """Rewrite a canonical JSON, optionally repairing the digest its sidecar records."""
    md = load_asset('make_results_md')
    data = json.loads(Path(path).read_text())
    mutate(data)
    Path(path).write_text(json.dumps(data))
    if restamp:
        side = json.loads(sidecar(path).read_text())
        side['outputs'][str(Path(path).resolve())] = md.sha(Path(path).read_bytes())
        sidecar(path).write_text(json.dumps(side))


MUTATIONS = {
    'sidecar_missing': lambda paths: sidecar(paths['table']).unlink(),
    'tampered': lambda paths: edit(paths['table'], lambda d: d['rows'].pop(), restamp=False),
    'exploratory': lambda paths: edit(paths['table'], lambda d: d.update(exploratory=True)),
    'deviations': lambda paths: edit(paths['table'], lambda d: d.update(deviations=['a run'])),
    'profile_digest': lambda paths: edit(paths['table'],
                                         lambda d: d['profile'].update(n_boot=1)),
    'table_coverage': lambda paths: edit(paths['table'], lambda d: d['rows'].pop()),
    'table_metric': lambda paths: edit(paths['table'],
                                       lambda d: d['rows'][0]['metrics'].pop('log_mse')),
    'pairs_reconverge': lambda paths: edit(paths['pairs'][0],
                                           lambda d: d.update(reconverge_required=['EDT K=8'])),
    'pairs_not_final': lambda paths: edit(paths['pairs'][1], lambda d: d.update(final=False)),
    'pairs_verdict': lambda paths: edit(paths['pairs'][2],
                                        lambda d: d.update(verdict='non-inferior')),
    'pairs_decision': lambda paths: edit(paths['pairs'][0],
                                         lambda d: d.update(decision_driving=True)),
    'pairs_coverage': lambda paths: edit(paths['pairs'][1], lambda d: d['cells'].pop()),
    'pairs_exploratory': lambda paths: edit(paths['pairs'][2],
                                            lambda d: d.update(exploratory=True)),
    'unseen_coverage': lambda paths: edit(paths['unseen'], lambda d: d['rows'].pop()),
    'unseen_binding': lambda paths: paths['binding'].write_text(
        json.dumps(dict(schema_version=1, git_HEAD='b' * 40, results=[]))),
}


@pytest.mark.parametrize('mutation', sorted(MUTATIONS))
def test_the_generator_refuses_unbound_or_provisional_input(record_inputs, mutation):
    md = load_asset('make_results_md')
    MUTATIONS[mutation](record_inputs)
    with pytest.raises((ValueError, OSError, KeyError)):
        md.arguments(argv(record_inputs))


@pytest.mark.parametrize('name,message', [('duplicate', 'duplicate canonical input'),
                                          ('overlap', 'output overlaps canonical input')])
def test_the_generator_refuses_a_duplicate_input_or_an_overlapping_output(record_inputs,
                                                                          name, message):
    md = load_asset('make_results_md')
    changes = dict(pairs=record_inputs['pairs'][:2] + record_inputs['pairs'][1:2]) \
        if name == 'duplicate' else dict(out=record_inputs['table'])
    with pytest.raises(ValueError, match=message):
        md.arguments(argv(record_inputs, **changes))


def test_an_unseen_table_the_exp04_report_does_not_bind_is_refused(record_inputs):
    """Its own sidecar is repaired; only the binding report still names the old digest."""
    md = load_asset('make_results_md')
    edit(record_inputs['unseen'], lambda data: data['rows'][0].update(label='Edited'))
    with pytest.raises(ValueError, match='not the one the exp_04 report binds'):
        md.arguments(argv(record_inputs))


def test_only_one_pairing_of_a_missing_one_is_refused(record_inputs):
    md = load_asset('make_results_md')
    with pytest.raises(ValueError, match='incomplete pairing coverage'):
        md.arguments(argv(record_inputs, pairs=record_inputs['pairs'][:2]))
