"""Record presentation uses real producer functions on synthetic CPU data."""
import importlib
import json
import re
import sys
from pathlib import Path

import pytest
from test_paired_compare import admission_fixture
from test_results_table import table_fixture
from tools import paired_compare as pc, results_table as rt
from tools.exp04_profiles import get_profile, json_value

ASSETS = Path(__file__).resolve().parents[1] / 'worklog/worklog_yixun/exp_04_yaw_aug_xrir_claude/yaw_aug_xrir_results_assets'
sys.path.insert(0, str(ASSETS))


@pytest.fixture
def record_inputs(table_fixture, tmp_path):
    table, admitted = rt.build_table(table_fixture.directories)
    table_path = tmp_path / 'table.json'
    rt.write_outputs(table, admitted, table_path, tmp_path / 'table.md')
    paths = {}
    for name in ('H1_K8', 'H1_K1', 'H2_K8', 'TOST_K8'):
        profile = json_value(get_profile(name))
        profile['n_boot'] = 2000
        groups = [group for row, group in zip(table['rows'], admitted['groups'])
                  if row['num_shot'] == profile['num_shot'] and row['role'] in ('aug', 'control')]
        groups.reverse()  # TABLE_V1 is control, cyl, aug; paired analyses are aug, control.
        for group in groups:
            for run in group:
                run['P'] = {str(k): run['P']['0'] for k in (0, 32, 64, 128, 256, 384, 448, 480)}
        selected = dict(admitted, groups=groups[:1] if name == 'TOST_K8' else groups)
        result = dict(pc.analyze(profile, selected), profile_name=name)
        paths[name] = tmp_path / (name + '.json')
        pc.write_outputs(result, selected, paths[name], tmp_path / (name + '.txt'))
    paths['TABLE_V1'] = table_path
    return paths


def test_markdown_canonical_and_stable(record_inputs, tmp_path):
    md = importlib.import_module('make_results_md')
    argv = sum(([flag, str(record_inputs[name])] for flag, name in md.INPUTS), [])
    output = tmp_path / 'results.md'
    md.main(argv + ['--out', str(output)])
    first = output.read_text()
    md.main(argv + ['--out', str(output)])
    assert first == output.read_text() and first.startswith('generated by make_results_md.py from ')
    assert all(word in first for word in ('ρ', 'D_k', 'non-inferior', 'equivalent', 'superiority', 'convergence', '±'))
    numbers = lambda s: set(re.findall(r'(?<![\w])[-+]?\d+(?:\.\d+)?(?:e[-+]?\d+)?(?![\w])', s))
    source = ''.join(p.read_text() + Path(str(p) + '.provenance.json').read_text() for p in record_inputs.values())
    assert numbers(first.split('\n', 1)[1]) <= numbers(source)


@pytest.mark.parametrize('mutation', ['missing', 'tamper', 'exploratory', 'verdict', 'profile', 'closure', 'coverage', 'gate'])
def test_markdown_refusals(record_inputs, mutation):
    md = importlib.import_module('make_results_md')
    path = record_inputs['H1_K8']
    side = Path(str(path) + '.provenance.json')
    data, receipt = json.loads(path.read_text()), json.loads(side.read_text())
    if mutation == 'missing':
        side.unlink()
    else:
        if mutation == 'exploratory': data['exploratory'] = True
        if mutation == 'verdict': data.pop('verdict')
        if mutation == 'coverage': data['cells'].pop()
        if mutation == 'gate': data['cells'][0]['convergence']['decision']['passed'] = False
        if mutation == 'profile': receipt['profile_digest'] = 'bad'
        if mutation == 'closure': receipt['producer']['sha256'] = 'bad'
        path.write_text(json.dumps(data))
        if mutation != 'tamper': receipt['outputs'][str(path)] = md.sha(path.read_bytes())
        side.write_text(json.dumps(receipt))
    with pytest.raises((ValueError, OSError)):
        md.load(path, 'H1_K8')
    if mutation == 'verdict':
        assert md.load(path, 'H1_K8', True)[2]
        out = path.parent / 'draft.md'
        md.main(sum(([f, str(record_inputs[n])] for f, n in md.INPUTS), []) + ['--draft-ok', '--out', str(out)])
        assert 'DRAFT' in out.read_text()


@pytest.mark.parametrize('mutation', [None, 'manifest', 'completion', 'output', 'train_manifest',
                                    'train_output', 'probe', 'audit', 'approved', 'log', 'echo', 'incomplete', 'missing_digest'])
def test_binding_roundtrip_and_refusals(tmp_path, monkeypatch, mutation):
    binder = importlib.import_module('bind_provenance')
    checker = importlib.import_module('check_record')
    p = pc.provenance
    paths = {name: tmp_path / name for name in ('probe', 'audit', 'approved', 'log', 'reference')}
    for path in paths.values():
        path.write_text('{}')
    attempt, run = tmp_path / 'attempt', tmp_path / 'run'
    attempt.mkdir(); run.mkdir()
    binding = lambda path: dict(path=str(path), sha256=p.sha256_file(path))
    inventory = dict(data_root=str(tmp_path), inventory=[], inventory_sha256=p._inventory_digest([]))
    train = dict(repo=str(tmp_path), mode='full', allow_dirty=False, reviewed_commit='unused',
                 source_closures={}, train_data_identity=inventory, effective_args={},
                 mutable_inputs={'probe_receipt': binding(paths['probe'])})
    p.write_manifest(attempt / 'train_manifest.json', train)
    for name in ['history.jsonl', 'args.json', 'effective_args.json'] + ['epoch_%03d.pth' % i for i in range(1, 13)]:
        (attempt / name).write_text('{}')
    train_outputs = {path.name: p.sha256_file(path) for path in attempt.iterdir()}
    p.write_manifest(attempt / 'completion.json', dict(train_manifest_sha256=train_outputs['train_manifest.json'],
        outputs=train_outputs, directory_listing=train_outputs, log=binding(paths['log'])))
    pins = dict(schema_version=1, checkpoints={'aug': binding(attempt / 'epoch_012.pth')}, closures={})
    monkeypatch.setattr(binder, 'load_approved_digests', lambda path: (pins, dict(binding(paths['approved']), git_blob='pinned')))
    fields = dict(repo=str(tmp_path), confirmatory=True, allow_dirty_used=False, schema_version=1,
        source_closures={}, evaluator_closure={'files': []}, data_identity=inventory,
        checkpoint=str(attempt / 'epoch_012.pth'), checkpoint_sha256=p.sha256_file(attempt / 'epoch_012.pth'),
        manifest_path=str(paths['reference']), manifest_file_sha256=p.sha256_file(paths['reference']),
        mutable_inputs={name: binding(attempt / filename) for name, filename in
                        [('train_manifest', 'train_manifest.json'), ('train_completion', 'completion.json')]})
    digest = p.write_manifest(run / 'eval_manifest.json', fields)
    outputs = {name: p.write_manifest(run / name, {'meta': {'eval_manifest_sha256': digest}})
               for name in ('metrics_yaw.json', 'per_sample_yaw.json')}
    completion = dict(eval_manifest_sha256=digest, schema_version=1, child_exit_status=0,
        confirmatory=True, allow_dirty_used=False, outputs=outputs, log=binding(paths['log']),
        directory_listing=sorted(['eval_manifest.json'] + list(outputs)))
    p.write_manifest(run / 'completion.json', completion)
    out = tmp_path / 'binding_report.json'
    argv = ['--runs', str(run), '--attempt', str(attempt), '--probe-receipt', str(paths['probe']),
            '--audit', str(paths['audit']), '--approved', str(paths['approved']), '--out', str(out)]
    binder.main(argv); original = out.read_bytes()
    checker.main([str(out)])
    with pytest.raises(FileExistsError): binder.main(argv)
    assert out.read_bytes() == original
    paths.update(manifest=run / 'eval_manifest.json', completion=run / 'completion.json',
                 output=run / 'metrics_yaw.json', train_manifest=attempt / 'train_manifest.json',
                 train_output=attempt / 'epoch_012.pth')
    if mutation in paths:
        paths[mutation].write_text(paths[mutation].read_text() + ' ')
    elif mutation == 'echo':
        p.write_completion(paths['output'], {'meta': {'eval_manifest_sha256': 'bad'}})
        completion['outputs']['metrics_yaw.json'] = p.sha256_file(paths['output'])
        p.write_completion(paths['completion'], completion)
    elif mutation == 'incomplete':
        (attempt / 'epoch_001.pth').unlink()
    elif mutation == 'missing_digest':
        completion['eval_manifest_sha256'] = None
        p.write_completion(paths['completion'], completion)
        with pytest.raises(ValueError): binder.main(argv[:-1] + [str(tmp_path / 'new_report.json')])
    if mutation:
        with pytest.raises((ValueError, OSError, KeyError)): checker.main([str(out)])
    else:
        monkeypatch.setattr(binder.subprocess, 'check_output', lambda *a, **k: pytest.fail('must retain original HEAD'))
        checker.main([str(out)])


@pytest.mark.parametrize('draft', [False, True])
def test_html_structure_values_and_stability(record_inputs, tmp_path, draft):
    page = importlib.import_module('make_results_html')
    from html.parser import HTMLParser
    class Cells(HTMLParser):
        def __init__(self):
            super().__init__()
            self.values, self.inside = [], False
        def handle_starttag(self, tag, attrs):
            if tag == 'td': self.inside = True
            assert not any(k in ('src', 'href') and v.startswith(('http', '//')) for k, v in attrs)
        def handle_endtag(self, tag):
            if tag == 'td': self.inside = False
        def handle_data(self, value):
            if self.inside: self.values.append(value)
    md = importlib.import_module('make_results_md')
    argv = sum(([flag, str(record_inputs[name])] for flag, name in md.INPUTS), [])
    if draft:
        path = record_inputs['H1_K8']
        data, side = json.loads(path.read_text()), Path(str(path) + '.provenance.json')
        data.pop('verdict')
        path.write_text(json.dumps(data))
        receipt = json.loads(side.read_text())
        receipt['outputs'][str(path)] = md.sha(path.read_bytes())
        side.write_text(json.dumps(receipt))
        argv += ['--draft-ok']
    out = tmp_path / 'yaw_aug_xrir_01_results.html'
    argv += ['--out', str(out), '--diag', str(record_inputs['TOST_K8'])]
    page.main(argv)
    first = out.read_text()
    page.main(argv)
    assert out.read_text() == first and ('DRAFT' in first) == draft
    assert 'prefers-color-scheme' in first and '<svg' in first and 'Provenance' in first and 'r_k' in first
    parser = Cells()
    parser.feed(first)
    expected = [md.display(v) for p in record_inputs.values() for _, _, rows in md.tables(json.loads(p.read_text())) for row in rows for v in row]
    assert all(value in parser.values for value in expected)


@pytest.mark.parametrize('mutation', ['missing', 'tamper', 'exploratory', 'verdict'])
def test_html_refusals(record_inputs, tmp_path, mutation):
    md, page = importlib.import_module('make_results_md'), importlib.import_module('make_results_html')
    path, out = record_inputs['H1_K8'], tmp_path / 'refused.html'
    side = Path(str(path) + '.provenance.json')
    data, receipt = json.loads(path.read_text()), json.loads(side.read_text())
    if mutation == 'missing': side.unlink()
    else:
        if mutation == 'exploratory': data['exploratory'] = True
        if mutation == 'verdict': data.pop('verdict')
        path.write_text(json.dumps(data))
        if mutation != 'tamper': receipt['outputs'][str(path)] = md.sha(path.read_bytes())
        side.write_text(json.dumps(receipt))
    with pytest.raises((ValueError, OSError)):
        page.main(sum(([f, str(record_inputs[n])] for f, n in md.INPUTS), []) + ['--out', str(out)])
    assert not out.exists()


def test_aggregate_verdict_is_not_assigned_to_individual_cells(record_inputs):
    md = importlib.import_module('make_results_md')
    for name in ('H1_K8', 'H1_K1', 'H2_K8'):
        data = json.loads(record_inputs[name].read_text())
        title, _, rows = next(md.tables(data))
        assert data['verdict'] in title
        assert all(row[9] == '—' for row in rows)
